### ISSUE TITLE
--exclude-fields option

### ISSUE THREAD

**Issue by llvtt** [mongodb-labs/mongo-connector#226]
Allow users to specify fields within a MongoDB document to exclude.

**Comment by sjalali** [comment]
Observed this behavior on nested fields:
{ "docType": "movie", "searchable": { "title": "Nebraska" }}  (part of much larger document)
In config.json: {"fields": ["searchable", "docType"] }

At startup, initial load, both docType and searchable make it to Elastic.
On subsequent updates, touching docType propagates the change. Touching searchable.title doesn't.
If I change fields to {"fields": ["searchable.title", "docType"] } it works.

Maybe we could have something like "searchable.*"  in fields to specify any changed sub-fields?
Otherwise all sub-fields would need to be listed in the filter.
Thanks!

**Comment by llvtt** [comment]
@sjalali That's a good suggestion! I'll make that into a new feature request (this particular issue is about excluding fields rather than including them).

**Comment by aherlihy** [comment]
https://github.com/mongodb-labs/mongo-connector/commit/4fe5de8d55a6c84d7465bc989f33696144ea9640

**Comment by Morriaty-The-Murderer** [comment]
Was this option still not fulfilled?
My mongo-connector version is 2.4, I used this option in command-line, but failed
```bash
/usr/local/bin/mongo-connector -m 10.10.20.155:27118 -t localhost:9200 -d elastic2_doc_manager -n ask.zd_topic -a usvr_sereader -p XXXXXXXXX --continue-on-error --exclude-fields pic_urls

mongo-connector: error: no such option: --exclude-fields
```

Thank you for help!
