### ISSUE TITLE
Nested field index will not update to Elasticsearch

### ISSUE THREAD

**Issue by ilooch** [mongodb-labs/mongo-connector#267]
I have the document as : 
```json
{
	"title" : "",
	"content" : "",
	"items" : [
		{"title" : "", "deleted" : ""},
		{"title" : "", "deleted" : ""},
		{"title" : "", "deleted" : ""},
		...
	]
}
```

And run mongo-connector with :
`mongo-connector -n notes.note -i title,content,items.title -m localhost:27017 -t localhost:9200 -d elastic_doc_manager`

The index of `items.title` will be created when create a new note, but when I change the title, the index will not updated.

And if run mongo-connector with :
`mongo-connector -n notes.note -i title,content,items -m localhost:27017 -t localhost:9200 -d elastic_doc_manager` ， everything work fine.

**Comment by llvtt** [comment]
Since "items" is an array, the "title" field of the first subdocument is
actually "items.0.title," not "items.title." The only way to pick up
changes on these inner fields is by watching for changes on "items" instead
of "items.title". There's a feature request for supporting wildcard
characters in "--fields" in #255.

**Comment by mygodbenben** [comment]
I have the similar question.
{
    "title" : "",
    "description" : "",
    "comments" : [
        {"description" : "", "author" : ""},
        {"description" : "", "author" : ""},
        {"description" : "", "author" : ""},
        ...
    ]
}
I want to index the "comments.description". But i still got the issue while i watched for changes on "comments" instead of "comments.description".
Because the updated top level field is "comments.2" not "comments" in the oplog, 
{ "ts" : Timestamp(1435152901, 4), "h" : NumberLong("4003465219120051278"), "v" : 2, "op" : "u", "ns" : "blog.blog_entry", "o2" : { "_id" : ObjectId("558aacaf20d3d217ac360ad3") }, "o" : { "$set" : { "comments.2" : { "id" : NumberLong(77), "creation_date" : ISODate("2015-06-24T13:35:01.367Z"), "creator_user_id" : NumberLong(8), "anonymous_ind" : false, "description" : "this is a new test comment" } } } }

**Comment by llvtt** [comment]
@mygodbenben 
You're right that the unwinding of the "comments" array not interact nicely with `--fields`. In order to catch the updates on any one of the sub-documents in "comments", you won't be able to use `--fields`. Otherwise, you need to explicitly mention which buckets in the "comments" array you're interested in seeing, e.g., `--fields comments.0,comments.1,...`, which isn't a pretty solution. Hopefully this will be better when mongo-connector gets a `--exclude-fields` option.

**Comment by aherlihy** [comment]
Hello! 

We have added support for nested fields [(here](https://github.com/mongodb-labs/mongo-connector/commit/4fe5de8d55a6c84d7465bc989f33696144ea9640) although not traversing arrays, so "times.0.title" will not be supported, neither are wildcards). 

I'm going to close this issue due to inactivity, and because there is an existing feature request for wildcards in the include/exclude options. However if you are still experiencing issues or have more questions, feel free to reopen or file a new issue.

Thank you!
