### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by hannelita** [mongodb-labs/mongo-connector#311]
Hi!
Is there a way to run the tests for a custom doc manager into a CI, like Travis?
Is there any recommendations to run a replica set properly into the CI?
Thanks in advance!

**Comment by llvtt** [comment]
Good question.

I'd suggest copying one of the existing doc manager tests, like `tests/test_elastic_doc_manager.py` as a starting point for creating your own test case.

The mongo connector tests spin up replica sets automatically using another project called [mongo-orchestration](https://github.com/10gen/mongo-orchestration). You can write your own wrapper around mongo-orchestration's REST api, or you can reuse mongo connector's own wrapper by putting the `tests` directory from this repository on your `PYTHONPATH`. Feel free to take ideas from [`setup_cluster.py`](https://github.com/10gen-labs/mongo-connector/blob/master/tests/setup_cluster.py) as well. Assuming you copy/reuse setup_cluster.py, you can use it like this:

    from tests.setup_cluster import ReplicaSet

to spin up a replica set (e.g., in the `setUp` method of your TestCase). A longer example:

    import unittest
    import mongo_connector
    from tests import ReplicaSet


    class MyDocManagerTestCase(unittest.TestCase):

        def setUp(self):
            self.rs = ReplicaSet().start()
            self.connector = mongo_connector.Connector(
                mongo_address=self.rs.uri,
                doc_managers=[MyDocManager()]
            )
    
        def tearDown(self):
            self.rs.stop()

**Comment by hannelita** [comment]
Thank you so much.
Adding the ReplicaSet() into the setup method is good idea. I'll give it a try and also post the necessary Travis configuration to have the tests running properly over there.
Thanks once again.

**Comment by llvtt** [comment]
Thank you! I'll add to the wiki my suggestions plus any additional
information you provide here about getting this set up.

**Comment by hannelita** [comment]
@llvtt 
Hi,
I've tried something like this for Travis [with the original mongo-connector project]
```
language: python
sudo: false
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip3 install --upgrade bson"
  - "pip3 install --upgrade pymongo"
  - "pip3 install mongo-orchestration"
services:
  - elasticsearch

before_script:
  - mongo-orchestration start
  - python setup.py install
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=3.6.1 bash
# command to run tests
script: python setup.py test
after_script:
  - mongo-orchestration stop
```

Worked pretty well (I had trouble with some tests - https://travis-ci.org/hannelita/mongo-connector/jobs/78077661 ) , but environment seems to be working properly.
Thanks for mongo-orchestration suggestion.

**Comment by llvtt** [comment]
Glad you're making progress! Let me try to shed some light on some of these
test results:

Errors like this:

TypeError: startswith first arg must be bytes or a tuple of bytes, not str

seem to be coming from Pysolr. This looks like a str vs unicode problem to
me.

The Elastic errors are probably related to a plugin being missing.
Synchronizing GridFS files requires the plugin described on this page:
https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch#support-for-gridfs

Errors like this:

TypeError: list indices must be integers, not str

are caused by an unexpected type of response from Mongo Orchestration.
Probably there was some kind of problem creating the cluster that the
setup_cluster code didn't check. FWIW, I usually run mongo-orchestration
with the "-s wsgiref" option for mongo-connector tests. This seems to make
them less flakey.

The 'test_synchronizer' tests pass for me, so I suspect that these failures
could be related to the "sleep" in the tests not being long enough.

Hope this helps!

**Comment by behackett** [comment]
> "pip3 install --upgrade bson"

PyMongo has it's own bson module. The one you are installing here is an incompatible third party library. The only reason things are working is that you install PyMongo immediately after, which overwrites the third party module. See the warning here:

https://api.mongodb.org/python/current/installation.html
