### ISSUE TITLE
Date parsing problem with Elasticsearch 2rc-1

### ISSUE THREAD

**Issue by speciose** [mongodb-labs/mongo-connector#347]
I know that it's not released yet but maybe it will be helpful in the future.
I've tried to connect mongodb to elasticsearch 2 and I've got this:
```
[2015-10-22 21:43:27,600][DEBUG][action.bulk][Fontanelle] [meteor][1] failed to execute bulk item (index) index {[meteor][sales][CA99], source[{"createdAt": 1445539373123.0, "name": "Goldner, Kautzer and Marks"}]}
MapperParsingException[failed to parse [createdAt]]; nested: IllegalArgumentException[Invalid format: "1445539373123.0" is malformed at "539373123.0"];
```
Seems like something wrong with mappings. Can't parse `Date.now()`
ElasticSearch 1.7.3 works well

**Comment by llvtt** [comment]
Elasticsearch 2.x is not yet supported. I'll make a new issue to track support for this.

**Comment by aherlihy** [comment]
Hello, support for Elastic 2.x is now live with Mongo-Connector 2.3.

In order to support Elastic 1.x and 2.x, the Elastic document manager has been pulled out of mongo-connector and is now located in a separate project.*

For more information on how to install and run the elastic doc managers, please see the Elastic doc manager documentation for the version of Elastic you prefer. These doc managers will only work with mongo-connector 2.3.0+.

Elastic 1.x doc manager: https://github.com/mongodb-labs/elastic-doc-manager

Elastic 2.x doc manager: https://github.com/mongodb-labs/elastic2-doc-manager

Hopefully this will solve your issue, but if not, feel free to reopen or file a new issue. Thank you!
