### ISSUE TITLE
Support Elastic 2.x

### ISSUE THREAD

**Issue by llvtt** [mongodb-labs/mongo-connector#351]

**Comment by marcinkubica** [comment]
Yes pretty please!!!

Kibana is using ES2 for some longer time already and there are people using your connector and following upgrades of ELK stack versions :D

**Comment by speciose** [comment]
Agree with previous speech. Any news on this topic? Waiting for ElasticSearch 2 support

**Comment by JuHwon** [comment]
+1

**Comment by ronaldploeger** [comment]
+1

**Comment by tmatei** [comment]
any updates?

**Comment by marcinkubica** [comment]
Yeah, would be great to know even a rough ETA.



-- 
Sent from Gmail Mobile

**Comment by aherlihy** [comment]
Hello! I will be working on elastic 2 support starting Monday, and will hopefully be done in the next few weeks.

**Comment by marcinkubica** [comment]
@aherlihy

Cool! Let me know if you need a tester - happy to help as I use it daily on
prod. :)

Marcin

>

-- 
Sent from Gmail Mobile

**Comment by tmatei** [comment]
@aherlihy any updates?

**Comment by aherlihy** [comment]
@tmatei unfortunately not, we got held up with some issues with the PyMongo 3 upgrade. This issue is next up however.

**Comment by tmatei** [comment]
@aherlihy sorry to bug you but just checking on status.

**Comment by marcinkubica** [comment]
Elasting is airing next release (v5) already.




-- 
Sent from Gmail Mobile

**Comment by oxymor0n** [comment]
+1

Support for 2.x would be great, since there's quite a bit of enhancement there, and it'd let us use kibana with it easily.

However, do take note that Elastic just announced yet another realignment of their software versions, so the next major Elasticsearch would be v5.0. Idk if there's gonna be any breaking changes, but if you haven't started on this yet, it might helps to look at the proposed change in v5.0 first so you can have the best compatibility.

**Comment by behackett** [comment]
There doesn't seem to be any mention of a v5 driver here:

https://github.com/elastic/elasticsearch-py

No dev branches related to it either.

**Comment by marcinkubica** [comment]
Probably worth considering indefinite retry for 429s and 503s ( as per notes for nex-gen log stash logstash pipeline https://www.elastic.co/blog/logstash-2-2-0-and-2-1-2-released )

**Comment by aherlihy** [comment]
Hello, work on elastic 2.x support is currently in code review.

**Comment by marcinkubica** [comment]
Cool!

-- 
Sent from Gmail Mobile

**Comment by tmatei** [comment]
any updates @aherlihy?

**Comment by aherlihy** [comment]
Hello, support for Elastic 2.x is now live with [Mongo-Connector 2.3.](https://github.com/mongodb-labs/mongo-connector/releases/tag/2.3.0)

In order to support Elastic 1.x and 2.x, the Elastic document manager has been pulled out of mongo-connector and is now located in a separate project.*

For more information on how to install and run the elastic doc managers, please see the Elastic doc manager documentation for the version of Elastic you prefer. These doc managers will only work with mongo-connector 2.3.0+.

Elastic 1.x doc manager: https://github.com/mongodb-labs/elastic-doc-manager

Elastic 2.x doc manager: https://github.com/mongodb-labs/elastic2-doc-manager

Sorry for the delay and thank you for your patience!

**Comment by marcinkubica** [comment]
\o/

**Comment by oxymor0n** [comment]
hallelujah!
