### ISSUE TITLE
Seems to do nothing

### ISSUE THREAD

**Issue by emrekanca** [mongodb-labs/mongo-connector#395]
When I run mongo-connector it prints this 
Logging to /var/log/mongo-connector/mongo-connector.log.
Nothing happens 
I tried stopping server and running this

`sudo mongo-connector -m localhost:27017 -t localhost:9200 -c /etc/mongo-connector.json -d elastic_doc_manager -o /home/emre/op.log -v
`
Still nothing in elasticsearch and nothing from verbose
How can I debug the problem?

**Comment by marcinkubica** [comment]
You need ops in oplog otherwise it wont dump anything. While its still on
try to add some record and remove it.

-- 
Sent from Gmail Mobile

**Comment by aherlihy** [comment]
Hello @emrekanca, did that answer your question?

**Comment by marcinkubica** [comment]
@aherlihy, while we at it, do you guys plan to addres it? It's not very
intuitive solution imho ;)




-- 
Sent from Gmail Mobile

**Comment by aherlihy** [comment]
Hello! When you started up mongo-connector, was there any data in your mongo collection? What does your config file look like?

**Comment by aherlihy** [comment]
Hello!

If there is nothing in the collection when Mongo-Connector is started and nothing is being added to the collection, we wouldn't expect anything to be logged (since nothing is happening). If you have data in your mongodb instance and nothing is happening, that is a problem :)

I'm going to close this issue due to inactivity, but please feel free to reopen/open a new one if this issue persists.
