### ISSUE TITLE
$addToSet and $pull objects being inserted into Elasticsearch

### ISSUE THREAD

**Issue by joshporter1** [mongodb-labs/mongo-connector#406]
I'm having an issue where mongo-connector is sending entries from the oplog that include `$addToSet` and `$pull` attributes. These documents are destroying my mapping (I have custom date formats declared), and eventually lead to errors and mongo-connector crashing. 

Before I upgraded my cluster to v2.2.0 and mongo-connector to 2.3, I did not have these issues and mongo-connector was working like a champ. I'm not sure if these kinds of oplog entries were handled before, but it'd be great to get a rundown on that and if this issue is caused by the mongo-connector 2.3/elastic2_doc_manager upgrade or an issue with mongo.

I'm currently running:
* mongo-connector 2.3
* elastic2-doc-manager 0.1.0
* mongodb 2.2.7
* elasticsearch 2.2.0

Example of a doc containing $addToSet
```json
{
    "ip_data": {
        "3": {
            "web_published": false
        }
    },
    "$addToSet": {
        "ip_data": {
            "web_published": true,
            "seen_first": "2016-02-18T15:43:56.114000",
            "active_last_seen": "2016-02-18T15:43:56.114000",
            "seen_last": "2016-02-18T15:43:56.114000",
            "version": "IPv4",
            "_id": "[redacted]"
        }
    }
}
```

Example of a doc containing $pull
```json
{
    "$pull": {
        "ip_data": {
            "_id": "[redacted]"
        }
    }
}
```

**Comment by aherlihy** [comment]
Hello!

I'm looking into this now. What server configuration do you have? Are you using a replica set or a sharded cluster?

**Comment by joshporter1** [comment]
The mongo instance isn't managed by me, but I believe it's using replica sets. If there's a command I could run to get those details, I can do that. 

Just curious, what does mongo-connector do if it runs into an item with $addToSet, but that original doc isn't in ES? Does it just throw it out? I don't have the data fully replicated, so the docs that have $addToSet might not exist yet.

**Comment by aherlihy** [comment]
Also, are these example docs in MongoDB or in your MongoDB instance or only in Elastic? If not, what do the documents in MongoDB look like?

**Comment by joshporter1** [comment]
So mongo contains everything, and I'm trying to replicate a mongo collection in elastic. 

The mongo doc correlating to the doc in the intial post is below.
```json
{
  "_id" : "[redacted]",
  "first_seen" : "10/10/2014 16:40:55",
  "ip_data" : [{
      "_id" : "[redacted]",
      "version" : "IPv4",
      "seen_first" : "10/10/2014 16:40:55",
      "seen_last" : "10/10/2014 16:40:55",
      "web_published" : false,
      "active_last_seen" : "10/10/2014 16:40:55"
    }, {
      "_id" : "[redacted]",
      "version" : "IPv4",
      "seen_first" : "2/18/2016 10:43:56",
      "seen_last" : "2/18/2016 10:43:56",
      "web_published" : true,
      "active_last_seen" : "2/18/2016 10:43:56"
    }]
}
```

This exists in mongo, but not yet in elastic, and the doc in the original post ends up getting indexed.

**Comment by aherlihy** [comment]
Hello!

Would it be possible for you to run:

`db.getSiblingDB("local").oplog.rs.find({"o.$push": {"$exists": true}}).toArray()`

and

`db.getSiblingDB("local").oplog.rs.find({"o.$addToList": {"$exists": true}}).toArray()`

on your mongo instance? Its possible that this query might take awhile since the oplog doesn't have indexes. If it returns a large list I only need a few documents, since it's probably the same thing that's happening for every operation.

Thanks for your patience!

**Comment by joshporter1** [comment]
When I try to run those, I get this error:

```
error: { "$err" : "can't use 'local' database through mongos", "code" : 13644 } at src/mongo/shell/query.js:128
```

Not sure what's causing that, any ideas?

**Comment by aherlihy** [comment]
You need to connect directly to each of your shards in order to query the oplog.

How long have you been running MongoDB 2.2? Are you certain that every part of the cluster is running 2.2?

The reason I'm asking is that in order for you to have $addToSet or $push show up in your elastic instance, they would have to come from your mongodb oplog.  After MongoDB 2.2.7, the oplog can only contain idempotent operations - i.e. $set and $unset. The only way to get $addToSet or $push in your oplog is if you used those commands before upgrading to 2.2.7 and you have either a very large oplog or a replset with very low usage (because the oplog rolls over).

[Mongo-Connector only supports MongoDB version 2.4 and later](https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#what-versions-of-mongodb-are-supported-by-mongo-connector), so when reading the oplog we only check for $set and $unset in update operations. Update operations without either $set or $unset are treated as replacements, which is why the entire $push/$addToSet update command is getting treated as a document.

Hopefully we can come up with a way to get around this issue, but I don't know why this would be coming up when you update your elastic instance because this issue existed in the last elastic doc manager. I also am not sure why you've got old-style oplog operations if you've been running 2.2.7 - how big is your oplog? How often are operations being done on your collections?

Thank you!

**Comment by joshporter1** [comment]
So the mongo cluster isn't managed by me, we just have a mongos instance for our own use, but we don't house the actual cluster data. It makes it tough to answer some of the more detailed questions like oplog size and whatnot, unless I can grab that using the cli and some command. 

I did run the command you sent above on the mongos instance, but I guess since it's not a shard it didn't work. However, mongo-connector was working prior to me updating everything, and either those $push/$addToSet commands didn't exist or they were ignored. Before the update, I pulled down ~600m documents in a little less than a week, if that could help determine the oplog operation count. 

When mongo-connector read the oplog, does it read newest-oldest? If so, it's completely possible that the oplog is large and the operations are low, which is why after 600-700m documents it's hitting these operations.

**Comment by joshporter1** [comment]
Of course, if there's any way for me to get info about the oplog with mongo cli, let me know and I can run the commands.

**Comment by aherlihy** [comment]
How are you running mongo-connector if you only have access to the mongos?

**Comment by joshporter1** [comment]
I'm running it on the same machine as mongos, and it was able to connect. I'm not entirely sure about how the oplog works - mongos doesn't get updates for it? Could it be mongos is running as a replica set member and it's getting oplog updates that way?

**Comment by joshporter1** [comment]
Also, if it helps any, the dates on the documents that are being sent with the $push/$addToSet commands have timestamps that are within the past month, so that rules out the old document theory.

**Comment by aherlihy** [comment]
In order to work mongo-connector needs to be able to access the shards. If you run `sh.status()` on the mongos, you can find the addresses of the shards. Can you connect directly to these addresses?

**Comment by joshporter1** [comment]
Unfortunately no I cannot, since we don't manage them. I'm just curious how it was working before.. and how it didn't error out when trying to run mongo-connector.  

Just to make sure, the person who set up the mongos instance said [this](https://docs.mongodb.org/manual/reference/program/mongos/) is what we're using to connect to the cluster. 

And the command is below:

```
mongos --configdb [configserver1], [configserver2], [configserver3] --port 4000
```

From there, I use localhost:4000to connect either with mongo-connector or the mongo cli

**Comment by behackett** [comment]
@joshporter1, you can actually access the shards directly. If you couldn't mongo-connector wouldn't work, since it has to be able to directly connect to the shards to replicate data to the target system. It can't do that work though mongos. Please run sh.status(), connect to the primary of each shard listed in the "shards" list, and run the queries @aherlihy asked about earlier. 

Also, can you tell us what version of mongo-connector you were using before you upgraded to 2.3? And also what version of Elasticsearch you were using before upgrading to 2.2.0?

**Comment by joshporter1** [comment]
I misunderstood and thought I required ssh access to those servers, but I understand now. Sorry for the confusion - I'm working on connecting and running those queries now, and I'll post back with the results once the queries finish - they are taking quite a while! 

As for the versions before the upgrades...

* elasticsearch - __1.7.1__
* mongo-connector - __2.2__ - I installed it about a month ago

**Comment by joshporter1** [comment]
Example $addToSet oplog docs
```
[
  {
    "ts" : Timestamp(1441312887, 31),
    "h" : NumberLong("-111720189895634896"),
    "op" : "u",
    "ns" : "domains",
    "o2" : {
      "_id" : "sample1.domain.com"
    },
    "o" : {
      "$addToSet" : {
        "ip_data" : {
          "_id" : "2a00:1450:400f:805:0:0:0:2001",
          "version" : "IPv6",
          "seen_first" : ISODate("2015-09-03T20:41:26.814Z"),
          "seen_last" : ISODate("2015-09-03T20:41:26.814Z"),
          "web_published" : true,
          "active_last_seen" : ISODate("2015-09-03T20:41:26.814Z")
        }
      }
    }
  },
  {
    "ts" : Timestamp(1441312887, 32),
    "h" : NumberLong("4009748812559340465"),
    "op" : "u",
    "ns" : "domains",
    "o2" : {
      "_id" : "sample2.domain.com"
    },
    "o" : {
      "$addToSet" : {
        "ip_data" : {
          "_id" : "212.22.213.97",
          "version" : "IPv4",
          "seen_first" : ISODate("2015-09-03T20:41:26.856Z"),
          "seen_last" : ISODate("2015-09-03T20:41:26.856Z"),
          "web_published" : true,
          "active_last_seen" : ISODate("2015-09-03T20:41:26.856Z")
        }
      }
    }
  },
  {
    "ts" : Timestamp(1441312887, 38),
    "h" : NumberLong("-3657870658006369788"),
    "op" : "u",
    "ns" : "domains",
    "o2" : {
      "_id" : "sample3.domain.com"
    },
    "o" : {
      "$addToSet" : {
        "ip_data" : {
          "_id" : "2a01:1250:300f:802:1:0:0:2101",
          "version" : "IPv6",
          "seen_first" : ISODate("2015-09-03T20:41:26.856Z"),
          "seen_last" : ISODate("2015-09-03T20:41:26.856Z"),
          "web_published" : true,
          "active_last_seen" : ISODate("2015-09-03T20:41:26.856Z")
        }
      }
    }
  }
]
```

I wasn't able to find any $push docs on any of the shards, and I did notice there were drastically less of those, so perhaps they got rolled off.

**Comment by aherlihy** [comment]
I think you have pre-2.2.1 servers running in your cluster. The only way $addToSet could possibly end up in the oplog is to use pre-2.2.1 servers.

Like I mentioned before, [Mongo-Connector only supports MongoDB version 2.4 and later](https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#what-versions-of-mongodb-are-supported-by-mongo-connector), and since the oplog entries you have are from an earlier version, we are not going to add support for this.

**Comment by joshporter1** [comment]
Ah, you're probably right. I still don't know why it worked in the older version, but oh well. Thanks anyways! 

If I were to try to modify mongo-connector to ignore/skip documents that have anything except $set/$unset, would that be possible or a viable workaround? Just curious if I should bother or just scrap using mongo-connector altogether since there's old versions of mongo in the cluster.

**Comment by aherlihy** [comment]
It depends on your use case. As I mentioned earlier, documents without $set/$unset are treated like replace. If you were to ignore all oplog operations with $-operators that aren't set/unset, then those documents would never make it into elastic search. This might work for your application, it might not.

[This](https://github.com/mongodb-labs/elastic2-doc-manager/blob/master/mongo_connector/doc_managers/elastic2_doc_manager.py#L83) could be a good place to start.

**Comment by joshporter1** [comment]
I'll definitely look into that. I'd love to get mongo-connector/es2 doc manager working with docs from this old mongo cluster. Thanks again for your help! :)

**Comment by joshporter1** [comment]
Hello again, just one quick question. I was trying to look into the history of the original elastic-doc-manager and noticed there is no history. Is there any way for me to see [this file](https://github.com/mongodb-labs/elastic-doc-manager/blob/master/mongo_connector/doc_managers/elastic_doc_manager.py) before you upgraded it to support es2, and before you split the repo into es and es2 doc managers? Thanks!

**Comment by aherlihy** [comment]
http://stackoverflow.com/questions/2952507/can-github-show-the-history-of-changes-made-to-one-file-in-patch-form

**Comment by joshporter1** [comment]
Yes, I did that but it doesn't appear to have any history. [Link](https://github.com/mongodb-labs/elastic-doc-manager/commits/master/mongo_connector/doc_managers/elastic_doc_manager.py)

**Comment by aherlihy** [comment]
https://github.com/mongodb-labs/mongo-connector/commits/master/mongo_connector/doc_managers/elastic_doc_manager.py

**Comment by joshporter1** [comment]
Perfect, thank you. Didn't realize it was in that repo.
