### ISSUE TITLE
Multiple instances targeting different technologies

### ISSUE THREAD

**Issue by gsvarovsky** [mongodb-labs/mongo-connector#597]
Please can you clarify the rule in the FAQ for this use-case:
```
mongo-connector -n a.b -g A.B -d elastic_doc_manager -o elastic\oplog.timestamp
mongo-connector -n a.b -g C.D -d my_custom_doc_manager -o custom\oplog.timestamp
```
As far as I can see there's nothing for the two instances to contend on (e.g. local files, write-back to mongo). Please confirm? Thanks

**Comment by ShaneHarvey** [comment]
Mongo-connector never writes to the MongoDB cluster it reads from. The only contention is with the [oplog progress file](https://github.com/mongodb-labs/mongo-connector/wiki/Oplog-Progress-File) which is why each example has a different [`--oplog-ts`](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#oplogfile) option.

**Comment by gsvarovsky** [comment]
Thanks Shane!
