### ISSUE TITLE
How to dump a partial collection to target?

### ISSUE THREAD

**Issue by thephysicsriot** [mongodb-labs/mongo-connector#660]
Is it possible to use connector with Elasticsearch to index only a portion or subset of a collection? I have 500GB of data in one mongo collection, but I would like to index only the most recent 100GB and then tail the oplog like normal.

**Comment by ShaneHarvey** [comment]
It's not possible to do that with mongo-connector and I don't see it being possible since MongoDB doesn't have a way to retrieve the most recently updated documents in a regular collection. 

Instead you might be able to filter only the important fields (or exclude unimportant ones) to reduced the size of the documents. See https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#filtering-documents-per-namespace.
