### ISSUE TITLE
Plans to support elastic 6.0?

### ISSUE THREAD

**Issue by vittico** [mongodb-labs/mongo-connector#758]
Hello!

is there any plan to update to support elastic 6.0?

**Comment by vioan** [comment]
any update on that?

**Comment by aguyinmontreal** [comment]
ElasticSearch 6 is now the official version

**Comment by vittico** [comment]
excellent! thanks!

**Comment by vioan** [comment]
the README file doesn't confirm that :)

**Comment by aguyinmontreal** [comment]
@vittico @vioan   I'm not saying this issue should be closed! :D I'm saying this issue is more urgent now, because ElasticSearch 6 is no longer a Beta, it's the official supported version now!!

[ElasticSearch 6 doesn't allow "types" anymore](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html), so I really don't know how mongo-connector will handle "collections" now!  I would like to know as soon as possible!

**Comment by vioan** [comment]
@aguyinmontreal I realised that but perhaps @vittico thought that you are part of the developers team and you solve it 😄

**Comment by aguyinmontreal** [comment]
Someone should reopen this issue
